ci(BYT-5349): Enable StressTest in Community_stable

diff --git a/.codebase/pipelines/ci.yaml b/.codebase/pipelines/ci.yaml
--- a/.codebase/pipelines/ci.yaml
+++ b/.codebase/pipelines/ci.yaml
@@ -18,7 +18,7 @@ jobs:
           sync_bvc: false
           sync_aws: false
           sync_oss: false
-          envs: {CUSTOM_CMAKE_BUILD_TYPE: "Release"}
+          envs: {CUSTOM_CMAKE_BUILD_TYPE: "RelWithDebInfo"}
   
   FuntionalStatelessTest:
     name: FuntionalStatelessTest
@@ -138,3 +138,43 @@ jobs:
                 echo "::add-message level=error::$(cat /test_output/check_status.tsv)"
                 exit 1
               fi
+  
+  StressTest:
+    name: StressTest
+    image: hub.byted.org/bytehouse/clickhouse-stress-test:stable
+    depends: [scm_build]
+    steps:
+      - uses: actions/checkout
+        inputs:
+          depth: 1
+      - name: Download From SCM
+        commands:
+          - echo $(pwd)
+          - cd /
+          - CLICKHOUSE_VERSION=${{ Jobs["scm_build"].Steps["scm_build"].Outputs["version"] }}
+          - CLICKHOUSE_PREFIX="clickhouse"
+          - mkdir -p $CLICKHOUSE_PREFIX
+          - wget -q -O $CLICKHOUSE_PREFIX/clickhouse.tar.gz http://d.scm.byted.org/api/v2/download/ceph:dp.clickhouse.ch_vanilla_clang_dev_$CLICKHOUSE_VERSION.tar.gz
+          - tar zxf $CLICKHOUSE_PREFIX/clickhouse.tar.gz  --directory clickhouse
+          - rm $CLICKHOUSE_PREFIX/clickhouse.tar.gz
+      - name: Run FuntionalStressTest
+        commands:
+          - cd /
+          - cp /home/code/docker/test/stress/run.sh run.sh
+          - /bin/bash run.sh
+      - name: Upload Artifact
+        uses: actions/upload-artifact
+        inputs:
+          name: test_output
+          path: /test_output
+      - name: Analyse Result
+        commands:
+          - |
+            if [ $(cut -f1 /test_output/check_status.tsv) = 'success' ]
+            then
+              echo "::add-message level=info::all cases pass!"
+              exit 0
+            else
+              echo "::add-message level=error::$(cat /test_output/check_status.tsv)"
+              exit 1
+            fi
