ci(BYT-5349): enable codebase pipelines

diff --git a/.codebase/pipelines/ci.yaml b/.codebase/pipelines/ci.yaml
--- a/.codebase/pipelines/ci.yaml
+++ b/.codebase/pipelines/ci.yaml
@@ -7,6 +7,9 @@ jobs:
     name: SCM Build for clang11 ch_vanilla_debian_dev
     image: hub.byted.org/data-ci-debian:latest
     steps:
+      - uses: actions/checkout
+        inputs:
+          depth: 1
       - uses: actions/scm
         id: scm_build
         inputs:
@@ -16,3 +19,42 @@ jobs:
           sync_aws: false
           sync_oss: false
           envs: {CUSTOM_CMAKE_BUILD_TYPE: "Release"}
+  
+  FuntionalStatelessTest:
+    name: FuntionalStatelessTest
+    image: hub.byted.org/bytehouse/clickhouse-stateless-test:stable
+    depends: [scm_build]
+    steps:
+      - uses: actions/checkout
+        inputs:
+          depth: 1
+      - name: Download From SCM
+        commands:
+          - echo $(pwd)
+          - cd /
+          - CLICKHOUSE_VERSION=${{ Jobs["scm_build"].Steps["scm_build"].Outputs["version"] }}
+          - CLICKHOUSE_PREFIX="clickhouse"
+          - mkdir -p $CLICKHOUSE_PREFIX
+          - wget -q -O $CLICKHOUSE_PREFIX/clickhouse.tar.gz http://d.scm.byted.org/api/v2/download/ceph:dp.clickhouse.ch_vanilla_clang_dev_$CLICKHOUSE_VERSION.tar.gz
+          - tar zxf $CLICKHOUSE_PREFIX/clickhouse.tar.gz  --directory clickhouse
+          - rm $CLICKHOUSE_PREFIX/clickhouse.tar.gz
+      - name: Run FuntionalStatelessTest
+        commands:
+          - cd /
+          - /bin/bash run.sh
+      - name: Upload Artifact
+        uses: actions/upload-artifact
+        inputs:
+          name: test_output
+          path: /test_output
+      - name: Analyse Result
+        commands:
+          - |
+            if [ $(cut -f1 /test_output/check_status.tsv) = 'success' ]
+            then
+              echo "::add-message level=info::all cases pass!"
+              exit 0
+            else
+              echo "::add-message level=error::$(cat /test_output/check_status.tsv)"
+              exit 1
+            fi
