fix wrong test_output dir

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,7 +49,7 @@ jobs:
           mkdir queries
           cp -r $GITHUB_WORKSPACE/tests/queries/4_cnch_stateless queries/
           cp -r $GITHUB_WORKSPACE/tests/queries/shell_config.sh queries/
-          mkdir -p test_output
+          mkdir -p /test_output
       - name: Run ByConity FuntionalStateless
         continue-on-error: true
         run: |
@@ -57,8 +57,8 @@ jobs:
           export CLICKHOUSE_PORT_HTTP=8124
           export CLICKHOUSE_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.Gateway}}{{end}}' server-0)
           cd /CI/
-          ./clickhouse-test -b $GITHUB_WORKSPACE/build/programs/clickhouse --stop --hung-check --jobs 4 --order asc --print-time 2>&1 | ts '%Y-%m-%d %H:%M:%S' | tee -a test_output/test_result.txt
-          ./process_functional_tests_result.py || echo -e "failure\tCannot parse results" > test_output/check_status.tsv
+          ./clickhouse-test -b $GITHUB_WORKSPACE/build/programs/clickhouse --stop --hung-check --jobs 4 --order asc --print-time 2>&1 | ts '%Y-%m-%d %H:%M:%S' | tee -a /test_output/test_result.txt
+          ./process_functional_tests_result.py || echo -e "failure\tCannot parse results" > /test_output/check_status.tsv
       # - name: CNCH - FuntionalStateless (multi-workers + ClickhouseSQL + w/w.o optimizer)
       #   continue-on-error: true
       #   run: |
