Add statesless test with optimizer CI test suite

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -63,7 +63,7 @@ jobs:
           curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 $CLICKHOUSE_HOST:$CLICKHOUSE_PORT_HTTP
           echo "Check status of cluster"
           docker ps --filter name=$COMPOSE_PROJECT_NAME
-      - name: Run ByConity FuntionalStateless
+      - name: Run ByConity FuntionalStateless (w.o optimizer)
         continue-on-error: true
         run: |
           cd /CI/
@@ -76,6 +76,22 @@ jobs:
           mkdir -p /test_output
           ./clickhouse-test -b $GITHUB_WORKSPACE/build/programs/clickhouse --stop --hung-check --jobs 8 --order asc --print-time --client-option ${EXTRA_OPTIONS} 2>&1 | ts '%Y-%m-%d %H:%M:%S' | tee -a /test_output/test_result.txt
           ./process_functional_tests_result.py || echo -e "failure\tCannot parse results" > /test_output/check_status.tsv
+      - name: Run ByConity FuntionalStateless (w optimizer)
+        continue-on-error: true
+        run: |
+          mkdir -p ci_stateless_with_optimizer
+          cd ci_stateless_with_optimizer
+          cp -r $GITHUB_WORKSPACE/docker/test/stateless/process_functional_tests_result.py ./
+          cp -r $GITHUB_WORKSPACE/tests/clickhouse-test ./
+          mkdir queries
+          cp -r $GITHUB_WORKSPACE/tests/queries/4_cnch_stateless queries/
+          cp -r $GITHUB_WORKSPACE/tests/queries/shell_config.sh queries/
+          mkdir -p test_output
+          export EXTRA_OPTIONS='enable_optimizer_fallback=0 enable_optimizer_white_list=0 enable_optimizer=1'
+          ./clickhouse-test -b $GITHUB_WORKSPACE/build/programs/clickhouse --stop --hung-check --jobs 8 --order asc --print-time --client-option ${EXTRA_OPTIONS} 2>&1 | ts '%Y-%m-%d %H:%M:%S' | tee -a test_output/test_result.txt
+          ./process_functional_tests_result.py --in-results-dir ./test_output/ --out-results-file /test_output/stateless_with_optimizer_test_results.txt --out-status-file /test_output/check_status.tsv || echo -e "failure\tCannot parse results" > /test_output/check_status.tsv
+          cd ..
+          rm -rf ci_stateless_with_optimizer
       - name: Run ByConity ClickhouseSQL FuntionalStateless (w.o optimizer)
         continue-on-error: true
         run: |
