separate s3 with/without tenant tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -118,17 +118,28 @@ jobs:
           find ./queries  -name *.sql |xargs -I {}  sed -i "s/\${TENANT_DB_PREFIX}/$TENANT_DB_PREFIX/" {}
           find ./queries  -name *.reference |xargs -I {}  sed -i "s/\${TENANT_DB_PREFIX}/$TENANT_DB_PREFIX/" {}
           ./clickhouse-test --s3 --use-skip-list --tenant_id $TENANT_ID -b $GITHUB_WORKSPACE/build/programs/clickhouse --stop --hung-check --jobs 8 --order asc --print-time --single-server --client-option ${EXTRA_OPTIONS} tenant_id=$TENANT_ID 2>&1 | ts '%Y-%m-%d %H:%M:%S' | tee -a test_output/test_result.txt
-          echo "Running test without tenant information"
-          unset TENANT_ID
-          unset TENANT_DB_PREFIX
-          unset TENANT_DEFAULT_DB_PREFIX
-          unset TENANT_DEFAULT_DB_PREFIX_INQUOTE
-          unset TENANT_HTTP_DEFAULT_DB_PREFIX
-          ./clickhouse-test --s3 --use-skip-list --queries "queries_no_tenant" -b $GITHUB_WORKSPACE/build/programs/clickhouse --stop --hung-check --jobs 8 --order asc --print-time --single-server --client-option ${EXTRA_OPTIONS} 2>&1 | ts '%Y-%m-%d %H:%M:%S' | tee -a test_output/test_result.txt
           ./process_functional_tests_result.py --in-results-dir ./test_output/ --out-results-file /test_output/stateless_without_optimizer_s3_test_results.txt --out-status-file /test_output/check_status.tsv || echo -e "failure\tCannot parse results" > /test_output/check_status.tsv
-          mv test_output/test_result.txt /test_output/wo_optimizer_s3_test_result.txt
           cd ..
           rm -rf ci_stateless_without_optimizer_s3
+      - name: Run ByConity FuntionalStateless for S3 not tenant (w.o optimizer)
+        continue-on-error: true
+        run: |
+          mkdir -p ci_stateless_without_optimizer_s3_no_tenant
+          cd ci_stateless_without_optimizer_s3_no_tenant
+          export EXTRA_OPTIONS='enable_optimizer_fallback=0 enable_optimizer=0'
+          cp -r $GITHUB_WORKSPACE/docker/test/stateless/process_functional_tests_result.py ./
+          cp -r $GITHUB_WORKSPACE/tests/clickhouse-test ./
+          mkdir -p queries_no_tenant
+          cp -r $GITHUB_WORKSPACE/tests/queries/4_cnch_stateless_no_tenant queries_no_tenant/
+          cp -r $GITHUB_WORKSPACE/tests/queries/shell_config.sh queries_no_tenant/
+          # We need skip-list to skip some tests.
+          cp $GITHUB_WORKSPACE/tests/queries/skip_list.json queries_no_tenant/
+          mkdir -p test_output
+          ./clickhouse-test --s3 --use-skip-list --queries "queries_no_tenant" -b $GITHUB_WORKSPACE/build/programs/clickhouse --stop --hung-check --jobs 8 --order asc --print-time --single-server --client-option ${EXTRA_OPTIONS} 2>&1 | ts '%Y-%m-%d %H:%M:%S' | tee -a test_output/test_result.txt
+          ./process_functional_tests_result.py --in-results-dir ./test_output/ --out-results-file /test_output/stateless_without_optimizer_s3_no_tenant_test_results.txt --out-status-file /test_output/check_status.tsv || echo -e "failure\tCannot parse results" > /test_output/check_status.tsv
+          mv test_output/test_result.txt /test_output/wo_optimizer_s3_no_tenant_test_result.txt
+          cd ..
+          rm -rf ci_stateless_without_optimizer_s3_no_tenant
       - name: After S3 tests
         if: always()
         continue-on-error: true
